baseURL = "https://krishamoud.me"
languageCode = "en-us"
title = "Kris Hamoud"
theme = "krishamoud.me"
staticDir = ["static"]
googleAnalytics = "UA-155739943-1"

[Params]
  creator = "Kris Hamoud"
  company = "@ConvertKit"
  companyURL = "https://convertkit.com"
  description = "Air Nomad. Guy on the internet. Infrastructure engineer @ConvertKit"
  tagline = "Air Nomad. Guy on the internet. Infrastructure engineer"
  metadescription = "Used as 'description' meta tag for both home and index pages. If not set, 'description' will be used instead"
  aboutURL = "/pages/about/"
  image = "/cover.jpg"
  Avatar = "/images/profile.png"
  images = ["/cover.jpg"]

  [Params.social]
    twitter = "https://twitter.com/krishamoud"
    linkedin = "https://linkedin.com/in/kristopher-hamoud-17b34665"
    github = "https://github.com/krishamoud"
