baseURL = "https://krishamoud.me"
languageCode = "en-us"
title = "Kris Makes Things"
theme = "krishamoud"
staticDir = ["static"]

[Params]
  description = "Traveler. Guy on the internet. Infrastructure engineer @ConvertKit"
  bio = "Traveler. Guy on the internet. Infrastructure engineer @ConvertKit"
  metadescription = "Used as 'description' meta tag for both home and index pages. If not set, 'description' will be used instead"
  aboutURL = "/pages/about/"
  image = "/cover.jpg"
  profilePic = "/profile.jpg"
  author = "Valère JEANTET"
  authorlocation = "Paris, France"
  authorwebsite = "http://vjeantet.fr"
  authorbio= "my bio"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..."
  githubName = "vjeantet"
  twitterName = "vjeantet"
  # facebookName = ""
  # codepenName = ""
  # linkedinName = ""
  # stackoverflowId = ""
  # keybaseName = ""
  # flickrName = ""
  # instagramName = ""
  # email = ""
  # pinterestName = ""
  # googlePlusName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

  # Setting a value will load highlight.js and enable syntax highlighting using the style selected.
  # See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
  # A preview of above styles can be viewed at https://highlightjs.org/static/demo/
  hjsStyle = "default"

  [Params.social]
    twitter = "https://twitter.com/krishamoud"
    linkedin-in = "https://linkedin.com/in/kristopher-hamoud-17b34665"
    github-alt = "https://github.com/krishamoud"
